//export const BASE_URL = "http://localhost:5000" //flask
export const BASE_URL = "https://copycash.tk"
export const BUY_URL = BASE_URL + "/buy";
export const PAIR_URL = BASE_URL + "/paridades";
export const SAVE_CONFIGS = BASE_URL + "/config";
export const LOGIN = BASE_URL + "/api/login";
export const REFRESH = BASE_URL + "/api/refresh";
export const CHECK = BASE_URL + "/api/protected";
export const GET_CONFIGS = BASE_URL + "/info";
